In [13]:
import pandas as pd

dfs = []
names = ["ume-final", "ume2"]
for name in names:
    dfs.append(pd.read_json(f"../data/{name}.jsonl", lines=True))
df = pd.concat(dfs)
df

,idx,question,choice_A,choice_B,choice_C,choice_D,correct_answer,domain,label,task,...,_task_hash,_view_id,topic,vocabulary,choices,overall,answer,_timestamp,_annotator_id,_session_id
0,591,A savings account starts with \$300 and gains ...,8 weeks,12 weeks,24 weeks,30 weeks,B,Algebra,Linear functions,Evaluate a linear function given an input valu...,...,-2043517965,blocks,3,2.0,3.0,2.0,accept,1740844196,ume-final-catherine,ume-final-catherine
1,487,A biologist models the population of bacteria ...,The initial population of bacteria in the petr...,The minimum population the petri dish can sustain,The average population of bacteria over the fi...,The maximum population the petri dish can sustain,D,Advanced Math,Nonlinear Functions,For a quadratic or exponential function in a c...,...,1689464308,blocks,2,1.0,3.0,1.0,accept,1740847740,ume-final-catherine,ume-final-catherine
2,508,"A school club with 80 members, equally divided...",$\frac{12}{80}$,$\frac{12}{35}$,$\frac{12}{23}$,$\frac{12}{20}$,B,Problem-Solving and Data Analysis,Probability and conditional probability,"Use one- and two-way tables, area models, and ...",...,128649510,blocks,2,3.0,3.0,2.0,accept,1740847927,ume-final-catherine,ume-final-catherine
3,560,"Company A offers a starting salary of \$30,000...",Year 2,Year 3,Year 4,Year 5,B,Problem-Solving and Data Analysis,Two-Variable Data - Models and Scatterplots,Compare linear and exponential growth.,...,-21803035,blocks,3,3.0,3.0,2.0,accept,1740849204,ume-final-catherine,ume-final-catherine
4,685,For the system of equations\n\n$kx + 3y = 12$\...,$km\neq6$,$k+m\neq6$,$2m\neq3k$,$k\neq2$ and $m\neq3$,A,Algebra,Systems of two linear equations in two variables,For a system of linear equations in two variab...,...,120544885,blocks,3,3.0,1.0,2.0,accept,1740850250,ume-final-catherine,ume-final-catherine
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,696,The sum of Emma's age and her brother Liam's a...,9,11,12,13,C,Algebra,Systems of two linear equations in two variables,Create and use a system of two linear equation...,...,1567682942,blocks,3,3.0,3.0,3.0,accept,1742168291,ume2-jennifer,ume2-jennifer
463,703,A candle burns linearly over time. The equatio...,The time taken to burn 1 centimeter,The initial length of the candle,The time taken to burn the candle completely,The length burned each hour,D,Algebra,Linear functions,Make connections between an algebraic represen...,...,-40250147,blocks,3,3.0,3.0,3.0,accept,1742168332,ume2-jennifer,ume2-jennifer
464,705,A fruit stand sells apples for \$2 each and or...,4,6,8,10,C,Algebra,Systems of two linear equations in two variables,Fluently solve a system of linear equations in...,...,-1286134991,blocks,3,3.0,3.0,3.0,accept,1742168360,ume2-jennifer,ume2-jennifer
465,709,A tutor charges a one-time base fee of \$30 pl...,$C = 25 + 30h$,$C = 25h$,$C = 30 + 25h$,$C = 30h + 25$,C,Algebra,Linear functions,Identify or create a linear function to model ...,...,474635500,blocks,3,3.0,3.0,3.0,accept,1742168385,ume2-jennifer,ume2-jennifer
466,711,A theater sells adult tickets for \$12 and stu...,34,48,40,22,D,Algebra,Linear equations in two variables,Create and use a linear equation in two variab...,...,1111238106,blocks,3,3.0,2.0,2.0,accept,1742168482,ume2-jennifer,ume2-jennifer

In [21]:
df = df.replace("", pd.NA)
df["overall"] = pd.to_numeric(df["overall"], errors="coerce")
df["topic"] = pd.to_numeric(df["topic"], errors="coerce")
df["vocabulary"] = pd.to_numeric(df["vocabulary"], errors="coerce")
df["choices"] = pd.to_numeric(df["choices"], errors="coerce")


def filter_incomplete_responses(row):
    """Filter out rows with incomplete responses."""
    valid_values = [1, 2, 3]
    return (
        (row["overall"] in valid_values)
        & (row["topic"] in valid_values)
        & (row["vocabulary"] in valid_values)
        & (row["choices"] in valid_values)
    )

valid_df = df[df.apply(filter_incomplete_responses, axis=1)]

In [22]:
counts = valid_df.groupby("idx").size()
items = counts[counts < 2].index.tolist()
valid_df[valid_df["idx"].isin(items)]

Empty DataFrame
Columns: [idx, question, choice_A, choice_B, choice_C, choice_D, correct_answer, domain, label, task, task_label, question_model, distractor_model, question_orig, choice_A_orig, choice_B_orig, choice_C_orig, choice_D_orig, display_question, display_choice_A, display_choice_B, display_choice_C, display_choice_D, html, _input_hash, _task_hash, _view_id, topic, vocabulary, choices, overall, answer, _timestamp, _annotator_id, _session_id]
Index: []

[0 rows x 35 columns]